# Generated by Django 4.2.2 on 2023-06-23 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_alter_message_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='MrtMemoMaker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_a', models.CharField(max_length=5)),
                ('time_b', models.CharField(max_length=5)),
                ('content_c', models.CharField(max_length=100)),
            ],
        ),
    ]
