# Generated by Django 4.2.2 on 2023-06-23 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_mrtmemomaker'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MrtMemoMaker',
        ),
    ]
